controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController

robot_controller:
  ros__parameters:
    joints:
      - joint_lower_arm
      - joint_upper_arm
      - joint_shoulder_drive
      - joint_rotary_yoke
      - joint_wrist_modul
      - joint_gripper_actuator
      - joint_gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
